'use client';

import { useState } from 'react';
import { api } from '@/lib/api';


type View = 'landing' | 'dashboard';

export default function AffiliatesPage() {
  const [view, setView] = useState<View>('landing');
  const [stats, setStats] = useState<any>(null);
  const [formData, setFormData] = useState({ email: '', companyName: '', website: '' });
  const [submitted, setSubmitted] = useState(false);
  const [isLoading, setIsLoading] = useState(false);

  const handleRegister = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsLoading(true);
    try {
      await api.post('/affiliates/register', formData);
      setSubmitted(true);
    } catch {}
    setIsLoading(false);
  };

  const loadDashboard = async () => {
    setView('dashboard');
    setIsLoading(true);
    try {
      const { data } = await api.get('/affiliates/stats');
      setStats(data.data);
    } catch {}
    setIsLoading(false);
  };

  // Landing Page
  if (view === 'landing' && !submitted) {
    return (
      <div className="max-w-4xl mx-auto space-y-8">
        {/* Hero */}
        <div className="card bg-gradient-to-r from-brand-600 to-brand-800 border-0 text-center py-12">
          <h1 className="text-3xl font-bold mb-3">CryptoBet Affiliate Program</h1>
          <p className="text-gray-200 max-w-lg mx-auto mb-6">
            Earn up to 25% revenue share commission by referring players to CryptoBet. Get paid in crypto with no limits.
          </p>
          <button onClick={() => document.getElementById('register-form')?.scrollIntoView({ behavior: 'smooth' })} className="btn-primary px-8 py-3">
            Become an Affiliate
          </button>
        </div>

        {/* Benefits */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {[
            { title: 'Up to 25% Revenue Share', desc: 'Earn a percentage of the net revenue generated by your referred players. No cap on earnings.' },
            { title: 'Real-Time Analytics', desc: 'Track clicks, registrations, deposits, and commissions in your personalized dashboard.' },
            { title: 'Crypto Payments', desc: 'Get paid in BTC, ETH, USDT, or any supported cryptocurrency. Fast, no fees.' },
          ].map((benefit) => (
            <div key={benefit.title} className="card text-center">
              <h3 className="font-bold text-sm mb-2">{benefit.title}</h3>
              <p className="text-xs text-gray-500">{benefit.desc}</p>
            </div>
          ))}
        </div>

        {/* Registration Form */}
        <div id="register-form" className="card max-w-md mx-auto">
          <h2 className="text-lg font-bold mb-4 text-center">Apply Now</h2>
          <form onSubmit={handleRegister} className="space-y-4">
            <div>
              <label className="text-xs text-gray-400 mb-1 block">Email</label>
              <input type="email" required value={formData.email} onChange={(e) => setFormData(p => ({ ...p, email: e.target.value }))} className="input" />
            </div>
            <div>
              <label className="text-xs text-gray-400 mb-1 block">Company Name (optional)</label>
              <input type="text" value={formData.companyName} onChange={(e) => setFormData(p => ({ ...p, companyName: e.target.value }))} className="input" />
            </div>
            <div>
              <label className="text-xs text-gray-400 mb-1 block">Website (optional)</label>
              <input type="url" value={formData.website} onChange={(e) => setFormData(p => ({ ...p, website: e.target.value }))} className="input" placeholder="https://" />
            </div>
            <button type="submit" disabled={isLoading} className="btn-primary w-full py-2.5">
              {isLoading ? 'Submitting...' : 'Submit Application'}
            </button>
          </form>
        </div>

        <p className="text-center text-sm text-gray-500">
          Already an affiliate? <button onClick={loadDashboard} className="text-brand-400 hover:underline">Go to Dashboard</button>
        </p>
      </div>
    );
  }

  // Submitted confirmation
  if (submitted) {
    return (
      <div className="max-w-md mx-auto text-center py-20">
        <div className="card py-12">
          <div className="text-4xl mb-4">✓</div>
          <h1 className="text-xl font-bold mb-2">Application Submitted</h1>
          <p className="text-sm text-gray-400">We'll review your application and get back to you within 24-48 hours.</p>
        </div>
      </div>
    );
  }

  // Dashboard
  return (
    <div className="max-w-4xl mx-auto space-y-6">
      <h1 className="text-2xl font-bold">Affiliate Dashboard</h1>

      {stats && (
        <>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
            {[
              { label: 'Total Referred', value: stats.stats.totalReferred },
              { label: 'Total Revenue', value: `$${stats.stats.totalRevenue}` },
              { label: 'Total Commission', value: `$${stats.stats.totalCommission}` },
              { label: 'Total Earned', value: `$${stats.stats.totalEarned}` },
            ].map((s) => (
              <div key={s.label} className="card text-center">
                <p className="text-xs text-gray-500">{s.label}</p>
                <p className="text-lg font-bold font-mono text-accent-green">{s.value}</p>
              </div>
            ))}
          </div>

          <div className="card">
            <h2 className="text-sm font-semibold mb-3">This Month</h2>
            <div className="grid grid-cols-3 gap-4">
              <div>
                <p className="text-xs text-gray-500">New Players</p>
                <p className="font-bold">{stats.stats.monthly.newPlayers}</p>
              </div>
              <div>
                <p className="text-xs text-gray-500">Revenue</p>
                <p className="font-bold font-mono">${stats.stats.monthly.revenue}</p>
              </div>
              <div>
                <p className="text-xs text-gray-500">Commission</p>
                <p className="font-bold font-mono text-accent-green">${stats.stats.monthly.commission}</p>
              </div>
            </div>
          </div>

          <div className="card">
            <h2 className="text-sm font-semibold mb-2">Your Referral Link</h2>
            <div className="flex gap-2">
              <input type="text" readOnly value={`https://cryptobet.com/?ref=${stats.affiliate.id}`} className="input flex-1 font-mono text-sm" />
              <button onClick={() => navigator.clipboard.writeText(`https://cryptobet.com/?ref=${stats.affiliate.id}`)} className="btn-primary text-sm">Copy</button>
            </div>
          </div>

          {stats.affiliate.apiKey && (
            <div className="card">
              <h2 className="text-sm font-semibold mb-2">API Key</h2>
              <input type="text" readOnly value={stats.affiliate.apiKey} className="input font-mono text-xs" />
            </div>
          )}
        </>
      )}
    </div>
  );
}
